---
name: Crypt-Skip32
version: 0.12
author:
  - 'Eric Hammond <eric-cpan@thinksome.com>'
abstract: 32-bit block cipher based on Skipjack
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.8.0
build_requires:
  Test::More: 0.62
  Test::NoWarnings: 0.084
recommends:
  Crypt::CBC: 2.22
  Test::Distribution: 0
dynamic_config: 0
provides:
  Crypt::Skip32:
    file: lib/Crypt/Skip32.pm
    version: 0.12
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
